### ISSUE TITLE
broken link to user guide on main readme

### ISSUE THREAD

**Issue by robzach** [makersmakingchange/bubble-blower-fan#1]
The documentation table in the readme points to the user guide at <https://github.com/makersmakingchange/bubble-blower-fan/blob/main/Documentation/BubbleBlowerFan_Quick_Guide_v1.0.pdf>, but that's a 404. The correct URL appears to be <https://github.com/makersmakingchange/bubble-blower-fan/blob/main/Documentation/BubbleBlowerFan_User_Guide_v1.0.pdf>.

**Comment by jakemcivor** [comment]
Thanks! Fixed.
